//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChequeClient.RESTServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingInformation", Namespace="http://schemas.datacontract.org/2004/07/ChequeBusinessData.Entity")]
    [System.SerializableAttribute()]
    public partial class BillingInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ChequeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChequeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChequeClient.RESTServiceReference.MenuItem[] MenuItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ChequeDate {
            get {
                return this.ChequeDateField;
            }
            set {
                if ((this.ChequeDateField.Equals(value) != true)) {
                    this.ChequeDateField = value;
                    this.RaisePropertyChanged("ChequeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChequeNo {
            get {
                return this.ChequeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChequeNoField, value) != true)) {
                    this.ChequeNoField = value;
                    this.RaisePropertyChanged("ChequeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChequeClient.RESTServiceReference.MenuItem[] MenuItems {
            get {
                return this.MenuItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuItemsField, value) != true)) {
                    this.MenuItemsField = value;
                    this.RaisePropertyChanged("MenuItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItem", Namespace="http://schemas.datacontract.org/2004/07/ChequeBusinessData.Entity")]
    [System.SerializableAttribute()]
    public partial class MenuItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuDescription {
            get {
                return this.MenuDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuDescriptionField, value) != true)) {
                    this.MenuDescriptionField = value;
                    this.RaisePropertyChanged("MenuDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuName {
            get {
                return this.MenuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuNameField, value) != true)) {
                    this.MenuNameField = value;
                    this.RaisePropertyChanged("MenuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RESTServiceReference.IRESTChequeService")]
    public interface IRESTChequeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESTChequeService/SaveMenuItem", ReplyAction="http://tempuri.org/IRESTChequeService/SaveMenuItemResponse")]
        void SaveMenuItem(ChequeClient.RESTServiceReference.BillingInformation billingInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESTChequeService/MenuItem", ReplyAction="http://tempuri.org/IRESTChequeService/MenuItemResponse")]
        string MenuItem();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRESTChequeServiceChannel : ChequeClient.RESTServiceReference.IRESTChequeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RESTChequeServiceClient : System.ServiceModel.ClientBase<ChequeClient.RESTServiceReference.IRESTChequeService>, ChequeClient.RESTServiceReference.IRESTChequeService {
        
        public RESTChequeServiceClient() {
        }
        
        public RESTChequeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RESTChequeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESTChequeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESTChequeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveMenuItem(ChequeClient.RESTServiceReference.BillingInformation billingInfo) {
            base.Channel.SaveMenuItem(billingInfo);
        }
        
        public string MenuItem() {
            return base.Channel.MenuItem();
        }
    }
}
