//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChequeClient.SoapServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapServiceRef.ChequeSOAPServiceSoap")]
    public interface ChequeSOAPServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllMenuItemsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMenuItems", ReplyAction="*")]
        ChequeClient.SoapServiceRef.GetAllMenuItemsResponse GetAllMenuItems(ChequeClient.SoapServiceRef.GetAllMenuItemsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMenuItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMenuItems", Namespace="http://tempuri.org/", Order=0)]
        public ChequeClient.SoapServiceRef.GetAllMenuItemsRequestBody Body;
        
        public GetAllMenuItemsRequest() {
        }
        
        public GetAllMenuItemsRequest(ChequeClient.SoapServiceRef.GetAllMenuItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMenuItemsRequestBody {
        
        public GetAllMenuItemsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMenuItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMenuItemsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChequeClient.SoapServiceRef.GetAllMenuItemsResponseBody Body;
        
        public GetAllMenuItemsResponse() {
        }
        
        public GetAllMenuItemsResponse(ChequeClient.SoapServiceRef.GetAllMenuItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMenuItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllMenuItemsResult;
        
        public GetAllMenuItemsResponseBody() {
        }
        
        public GetAllMenuItemsResponseBody(string GetAllMenuItemsResult) {
            this.GetAllMenuItemsResult = GetAllMenuItemsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChequeSOAPServiceSoapChannel : ChequeClient.SoapServiceRef.ChequeSOAPServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChequeSOAPServiceSoapClient : System.ServiceModel.ClientBase<ChequeClient.SoapServiceRef.ChequeSOAPServiceSoap>, ChequeClient.SoapServiceRef.ChequeSOAPServiceSoap {
        
        public ChequeSOAPServiceSoapClient() {
        }
        
        public ChequeSOAPServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChequeSOAPServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChequeSOAPServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChequeSOAPServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChequeClient.SoapServiceRef.GetAllMenuItemsResponse ChequeClient.SoapServiceRef.ChequeSOAPServiceSoap.GetAllMenuItems(ChequeClient.SoapServiceRef.GetAllMenuItemsRequest request) {
            return base.Channel.GetAllMenuItems(request);
        }
        
        public string GetAllMenuItems() {
            ChequeClient.SoapServiceRef.GetAllMenuItemsRequest inValue = new ChequeClient.SoapServiceRef.GetAllMenuItemsRequest();
            inValue.Body = new ChequeClient.SoapServiceRef.GetAllMenuItemsRequestBody();
            ChequeClient.SoapServiceRef.GetAllMenuItemsResponse retVal = ((ChequeClient.SoapServiceRef.ChequeSOAPServiceSoap)(this)).GetAllMenuItems(inValue);
            return retVal.Body.GetAllMenuItemsResult;
        }
    }
}
