//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChequeServerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInformation
    {
        public long ID { get; set; }
        public long MENUID { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string CATEGORY { get; set; }
        public string CHEQUENO { get; set; }
        public Nullable<System.DateTime> CHEQUEDATE { get; set; }
    }
}
