//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChequeServerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public long ID { get; set; }
        public string MENUNAME { get; set; }
        public string MENUDESCRIPTION { get; set; }
        public string MENUCATEGORY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    }
}
