//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ChequeConsumer.ChequeSoapService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChequeSOAPServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ChequeSOAPService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllMenuItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllMenuItemsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveMenuItemBySaopOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChequeSOAPService() {
            this.Url = global::ChequeConsumer.Properties.Settings.Default.ChequeConsumer_ChequeSoapService_ChequeSOAPService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllMenuItemsCompletedEventHandler GetAllMenuItemsCompleted;
        
        /// <remarks/>
        public event GetAllMenuItemsListCompletedEventHandler GetAllMenuItemsListCompleted;
        
        /// <remarks/>
        public event SaveMenuItemBySaopCompletedEventHandler SaveMenuItemBySaopCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllMenuItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAllMenuItems() {
            object[] results = this.Invoke("GetAllMenuItems", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllMenuItemsAsync() {
            this.GetAllMenuItemsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllMenuItemsAsync(object userState) {
            if ((this.GetAllMenuItemsOperationCompleted == null)) {
                this.GetAllMenuItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllMenuItemsOperationCompleted);
            }
            this.InvokeAsync("GetAllMenuItems", new object[0], this.GetAllMenuItemsOperationCompleted, userState);
        }
        
        private void OnGetAllMenuItemsOperationCompleted(object arg) {
            if ((this.GetAllMenuItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllMenuItemsCompleted(this, new GetAllMenuItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllMenuItemsList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MenuItem[] GetAllMenuItemsList() {
            object[] results = this.Invoke("GetAllMenuItemsList", new object[0]);
            return ((MenuItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllMenuItemsListAsync() {
            this.GetAllMenuItemsListAsync(null);
        }
        
        /// <remarks/>
        public void GetAllMenuItemsListAsync(object userState) {
            if ((this.GetAllMenuItemsListOperationCompleted == null)) {
                this.GetAllMenuItemsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllMenuItemsListOperationCompleted);
            }
            this.InvokeAsync("GetAllMenuItemsList", new object[0], this.GetAllMenuItemsListOperationCompleted, userState);
        }
        
        private void OnGetAllMenuItemsListOperationCompleted(object arg) {
            if ((this.GetAllMenuItemsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllMenuItemsListCompleted(this, new GetAllMenuItemsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveMenuItemBySaop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveMenuItemBySaop(BillingInformation BillingInfo) {
            object[] results = this.Invoke("SaveMenuItemBySaop", new object[] {
                        BillingInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveMenuItemBySaopAsync(BillingInformation BillingInfo) {
            this.SaveMenuItemBySaopAsync(BillingInfo, null);
        }
        
        /// <remarks/>
        public void SaveMenuItemBySaopAsync(BillingInformation BillingInfo, object userState) {
            if ((this.SaveMenuItemBySaopOperationCompleted == null)) {
                this.SaveMenuItemBySaopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveMenuItemBySaopOperationCompleted);
            }
            this.InvokeAsync("SaveMenuItemBySaop", new object[] {
                        BillingInfo}, this.SaveMenuItemBySaopOperationCompleted, userState);
        }
        
        private void OnSaveMenuItemBySaopOperationCompleted(object arg) {
            if ((this.SaveMenuItemBySaopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveMenuItemBySaopCompleted(this, new SaveMenuItemBySaopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MenuItem {
        
        private long idField;
        
        private string menuNameField;
        
        private string menuDescriptionField;
        
        private string categoryField;
        
        private decimal priceField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string MenuName {
            get {
                return this.menuNameField;
            }
            set {
                this.menuNameField = value;
            }
        }
        
        /// <remarks/>
        public string MenuDescription {
            get {
                return this.menuDescriptionField;
            }
            set {
                this.menuDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BillingInformation {
        
        private string chequeNoField;
        
        private System.DateTime chequeDateField;
        
        private MenuItem[] menuItemsField;
        
        /// <remarks/>
        public string ChequeNo {
            get {
                return this.chequeNoField;
            }
            set {
                this.chequeNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ChequeDate {
            get {
                return this.chequeDateField;
            }
            set {
                this.chequeDateField = value;
            }
        }
        
        /// <remarks/>
        public MenuItem[] MenuItems {
            get {
                return this.menuItemsField;
            }
            set {
                this.menuItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetAllMenuItemsCompletedEventHandler(object sender, GetAllMenuItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllMenuItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllMenuItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetAllMenuItemsListCompletedEventHandler(object sender, GetAllMenuItemsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllMenuItemsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllMenuItemsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MenuItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MenuItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void SaveMenuItemBySaopCompletedEventHandler(object sender, SaveMenuItemBySaopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveMenuItemBySaopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveMenuItemBySaopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591